### ISSUE TITLE
Improvisations Suggested

### ISSUE THREAD

**Issue by Ved-programmer** [crypto-navdeep/Key-Logger#2]
Here are a few suggestions to improve the code quality

1. Remove repetetive code
2. Remove redundant/unnecessary comments
3. Add blank lines in certain places to differentiate between separate pieces of code and for easability of reading

**Comment by Ved-programmer** [comment]
fixed issues here -> https://github.com/crypto-navdeep/Key-Logger/pull/1

**Comment by crypto-navdeep** [comment]
Hi Ved! I Just Checked it now.

Thanks for your contribution, I'm currently busy now, I'll check it later.
Nevertheless, Thanks a lot for your time and effort for reviewing the code, I'll check and merge PR as soon a possible.

Regards,
Navdeep.

**Comment by crypto-navdeep** [comment]
Fixed this at #1
